version: '3'

services:
  back:
    image: cassoni-backend:1.0
    container_name: back_django
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - cassoni-network
    volumes:
      - ./src:/app
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db

  back_nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    restart: always
    networks:
      - cassoni-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/back.conf:ro
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - back

  db:
    image: postgres:latest
    container_name: back_postgres
    env_file: .env.db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - cassoni-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  cassoni-network:
    driver: bridge
