# Generated by Django 5.0.2 on 2024-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inquery", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquery",
            options={"verbose_name": "InQuery", "verbose_name_plural": "InQueries"},
        ),
        migrations.AlterField(
            model_name="inquery",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
