# Generated by Django 5.0.2 on 2024-02-12 11:08

import app_settings.models.video
import ckeditor.fields
import utils.db.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Phone", "Phone"),
                            ("Email", "ایمیل"),
                            ("Address", "Address"),
                        ],
                        max_length=8,
                        verbose_name="Type",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="Value")),
            ],
            options={
                "ordering": ["create_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContainerVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to=app_settings.models.video.video_directory_path,
                        validators=[utils.db.validators.validate_video_file_extension],
                        verbose_name="Video File",
                    ),
                ),
                (
                    "filter_bw",
                    models.BooleanField(
                        default=False, verbose_name="Have Filter Black & White?"
                    ),
                ),
            ],
            options={
                "ordering": ["create_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Options",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("OurStory", "OurStory")],
                        max_length=10,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                ("value", ckeditor.fields.RichTextField(verbose_name="Value")),
            ],
            options={
                "ordering": ["create_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "application",
                    models.CharField(
                        choices=[
                            ("Telegram", "Telegram"),
                            ("WhatsApp", "WhatsApp"),
                            ("YouTube", "YouTube"),
                            ("Instagram", "Instagram"),
                            ("Twitter", "Twitter"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Application",
                    ),
                ),
                ("application_url", models.URLField(verbose_name="Application URL")),
            ],
            options={
                "ordering": ["create_at"],
                "abstract": False,
            },
        ),
    ]
