# Generated by Django 5.0.2 on 2024-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contact"},
        ),
        migrations.AlterModelOptions(
            name="containervideo",
            options={
                "verbose_name": "Container Video",
                "verbose_name_plural": "Container Video",
            },
        ),
        migrations.AlterModelOptions(
            name="options",
            options={"verbose_name": "Option", "verbose_name_plural": "Options"},
        ),
        migrations.AlterModelOptions(
            name="socialmedia",
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
            },
        ),
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("Phone", "Phone"),
                    ("Email", "Email"),
                    ("Address", "Address"),
                ],
                max_length=8,
                verbose_name="Type",
            ),
        ),
    ]
