# Generated by Django 5.0.2 on 2024-02-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_settings",
            "0002_alter_contact_options_alter_containervideo_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("type",),
                "verbose_name": "Contact",
                "verbose_name_plural": "Contact",
            },
        ),
    ]
