# Generated by Django 5.0.2 on 2024-03-02 11:55

import app_settings.models.grid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0003_alter_contact_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerGridImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=app_settings.models.grid.image_directory_path,
                        verbose_name="Image File",
                    ),
                ),
                ("caption", models.CharField(max_length=128, verbose_name="Caption")),
                ("alt", models.CharField(max_length=128, verbose_name="Alt")),
            ],
            options={
                "verbose_name": "Container Grid Image",
                "verbose_name_plural": "Container Grid Image",
            },
        ),
    ]
