# Generated by Django 5.0.2 on 2024-03-11 15:52

import app_settings.models.grid
import ckeditor.fields
import datetime
import django.utils.timezone
import utils.db.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_containergridimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='containergridimage',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='containergridimage',
            name='filter_bw',
            field=models.BooleanField(default=False, verbose_name='Video Have Filter Black & White?'),
        ),
        migrations.AddField(
            model_name='containergridimage',
            name='main_video',
            field=models.FileField(upload_to=app_settings.models.grid.video_directory_path, validators=[utils.db.validators.validate_video_file_extension], verbose_name='Video File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='containergridimage',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug Link Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='containergridimage',
            name='video_content',
            field=ckeditor.fields.RichTextField(verbose_name='Video Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='containergridimage',
            name='image',
            field=models.ImageField(upload_to=app_settings.models.grid.image_directory_path, verbose_name='Image File Cover'),
        ),
    ]
