# Generated by Django 5.0.2 on 2024-03-11 18:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_containergridimage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containergridimage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='containergridimage',
            name='video_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Video Content'),
        ),
    ]
