# Generated by Django 5.0.2 on 2024-03-11 18:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0006_alter_containergridimage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='value',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Value'),
        ),
    ]
