# Generated by Django 5.0.2 on 2024-03-12 09:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0007_alter_options_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containergridimage',
            name='video_content',
        ),
        migrations.AddField(
            model_name='containergridimage',
            name='image_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Image Content'),
            preserve_default=False,
        ),
    ]
