# Generated by Django 5.0.2 on 2024-03-12 09:07

import app_settings.models.grid
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0008_remove_containergridimage_video_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containergridimage',
            name='image_content',
        ),
        migrations.AddField(
            model_name='containergridimage',
            name='main_image',
            field=models.ImageField(upload_to=app_settings.models.grid.image_directory_path, verbose_name='Main Image File'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='containergridimage',
            name='main_image_alt',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Main Image Alt'),
        ),
        migrations.AddField(
            model_name='containergridimage',
            name='main_image_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Main Image Content'),
        ),
        migrations.AlterField(
            model_name='containergridimage',
            name='alt',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Alt'),
        ),
    ]
